using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Strings;

namespace VejleKommune.Code.Features.Bootstrap;

internal sealed record ResolvedCompositions(
    IContentType SeoMetadata,
    IContentType AccessibilityMetadata,
    IContentType TranslationMetadata,
    IContentType SchemaOrgOverride);

internal static class CompositionFactory
{
    public static async Task<ResolvedCompositions> CreateAllAsync(
        IContentTypeService contentTypeService,
        IShortStringHelper shortStringHelper,
        ResolvedDataTypes dataTypes)
    {
        var seo = BuildSeoMetadata(shortStringHelper, dataTypes);
        await contentTypeService.CreateAsync(seo, Constants.Security.SuperUserKey);

        var accessibility = BuildAccessibilityMetadata(shortStringHelper, dataTypes);
        await contentTypeService.CreateAsync(accessibility, Constants.Security.SuperUserKey);

        var translation = BuildTranslationMetadata(shortStringHelper, dataTypes);
        await contentTypeService.CreateAsync(translation, Constants.Security.SuperUserKey);

        var schemaOverride = BuildSchemaOrgOverride(shortStringHelper, dataTypes);
        await contentTypeService.CreateAsync(schemaOverride, Constants.Security.SuperUserKey);

        return new ResolvedCompositions(seo, accessibility, translation, schemaOverride);
    }

    private static ContentType BuildSeoMetadata(IShortStringHelper helper, ResolvedDataTypes dt)
    {
        var ct = new ContentType(helper, -1)
        {
            Key = DoctypeKeys.SeoMetadata,
            Alias = DoctypeKeys.SeoMetadataAlias,
            Name = "SEO metadata",
            Description = "SEO fields applied to all public-facing pages.",
            Icon = "icon-search",
            Variations = ContentVariation.Culture,
        };
        AddGroup(ct, "seo", "SEO");
        AddProperty(ct, helper, dt.Textstring, "metaTitle", "Meta title", "seo", ContentVariation.Culture);
        AddProperty(ct, helper, dt.Textarea, "metaDescription", "Meta description", "seo", ContentVariation.Culture);
        AddProperty(ct, helper, dt.Textstring, "metaGeneratedBy", "Meta generated by (provenance)", "seo", ContentVariation.Culture);
        return ct;
    }

    private static ContentType BuildAccessibilityMetadata(IShortStringHelper helper, ResolvedDataTypes dt)
    {
        var ct = new ContentType(helper, -1)
        {
            Key = DoctypeKeys.AccessibilityMetadata,
            Alias = DoctypeKeys.AccessibilityMetadataAlias,
            Name = "Accessibility metadata",
            Description = "Audit metadata produced by the Async analyze Pattern. Findings block list stubbed as plain text in Phase 0+1 (ADR-0011 scope deviation).",
            Icon = "icon-eye",
            Variations = ContentVariation.Culture,
        };
        AddGroup(ct, "accessibility", "Accessibility");
        AddProperty(ct, helper, dt.DateTimePicker, "lastAuditAt", "Last audit at", "accessibility", ContentVariation.Culture);
        AddProperty(ct, helper, dt.Textarea, "findings", "Findings (stub — will become a block list in Phase 5)", "accessibility", ContentVariation.Culture);
        return ct;
    }

    private static ContentType BuildTranslationMetadata(IShortStringHelper helper, ResolvedDataTypes dt)
    {
        var ct = new ContentType(helper, -1)
        {
            Key = DoctypeKeys.TranslationMetadata,
            Alias = DoctypeKeys.TranslationMetadataAlias,
            Name = "Translation metadata",
            Description = "Provenance fields produced by the Async transform Pattern (translation).",
            Icon = "icon-globe",
            Variations = ContentVariation.Culture,
        };
        AddGroup(ct, "translation", "Translation");
        AddProperty(ct, helper, dt.Textstring, "translationGeneratedBy", "Translation generated by (provenance)", "translation", ContentVariation.Culture);
        AddProperty(ct, helper, dt.DateTimePicker, "translationAcceptedAt", "Translation accepted at", "translation", ContentVariation.Culture);
        return ct;
    }

    private static ContentType BuildSchemaOrgOverride(IShortStringHelper helper, ResolvedDataTypes dt)
    {
        var ct = new ContentType(helper, -1)
        {
            Key = DoctypeKeys.SchemaOrgOverride,
            Alias = DoctypeKeys.SchemaOrgOverrideAlias,
            Name = "Schema.org override",
            Description = "Optional per-node overrides for the Schema enrichment Pattern. Default mappings live in code; this composition is the documented escape hatch.",
            Icon = "icon-code",
            Variations = ContentVariation.Culture,
        };
        AddGroup(ct, "schemaOrg", "Schema.org");
        AddProperty(ct, helper, dt.Textstring, "schemaTypeOverride", "Schema.org type override", "schemaOrg", ContentVariation.Nothing);
        AddProperty(ct, helper, dt.Textarea, "additionalJsonLd", "Additional JSON-LD (raw)", "schemaOrg", ContentVariation.Nothing);
        return ct;
    }

    private static void AddGroup(IContentTypeComposition ct, string alias, string name)
    {
        ct.AddPropertyGroup(alias, name);
    }

    private static void AddProperty(
        IContentTypeComposition ct,
        IShortStringHelper helper,
        IDataType dataType,
        string alias,
        string name,
        string groupAlias,
        ContentVariation variations)
    {
        var pt = new PropertyType(helper, dataType, alias)
        {
            Name = name,
            Mandatory = false,
            Variations = variations,
        };
        ct.AddPropertyType(pt, groupAlias);
    }
}
