using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Strings;

namespace VejleKommune.Code.Features.Bootstrap;

internal static class MediaTypeFactory
{
    public static async Task CreateAllAsync(
        IMediaTypeService mediaTypeService,
        IShortStringHelper shortStringHelper,
        ResolvedDataTypes dataTypes)
    {
        var image = BuildImage(shortStringHelper, dataTypes);
        await mediaTypeService.CreateAsync(image, Constants.Security.SuperUserKey);

        var document = BuildDocument(shortStringHelper, dataTypes);
        await mediaTypeService.CreateAsync(document, Constants.Security.SuperUserKey);
    }

    private static MediaType BuildImage(IShortStringHelper helper, ResolvedDataTypes dt)
    {
        var mt = new MediaType(helper, -1)
        {
            Key = DoctypeKeys.ImageMedia,
            Alias = DoctypeKeys.ImageMediaAlias,
            Name = "Vejle image",
            Description = "Image media extended with required alt-text + provenance fields for the Sync suggestion Pattern (alt text use case).",
            Icon = "icon-picture",
            AllowedAsRoot = true,
        };
        mt.AddPropertyGroup("imageContent", "Image");
        AddProperty(mt, helper, dt.ImageCropper, "umbracoFile", "Image file", "imageContent", mandatory: true);
        AddProperty(mt, helper, dt.Textstring, "altText", "Alt text", "imageContent", mandatory: false);
        AddProperty(mt, helper, dt.Textstring, "altGeneratedBy", "Alt generated by (provenance)", "imageContent", mandatory: false);
        AddProperty(mt, helper, dt.DateTimePicker, "altAcceptedAt", "Alt accepted at", "imageContent", mandatory: false);
        return mt;
    }

    private static MediaType BuildDocument(IShortStringHelper helper, ResolvedDataTypes dt)
    {
        var mt = new MediaType(helper, -1)
        {
            Key = DoctypeKeys.DocumentMedia,
            Alias = DoctypeKeys.DocumentMediaAlias,
            Name = "Vejle document",
            Description = "Word/PDF document used as input by the Generative pipeline Pattern. Stored under /imports/.",
            Icon = "icon-document",
            AllowedAsRoot = true,
        };
        mt.AddPropertyGroup("documentContent", "Document");
        AddProperty(mt, helper, dt.UploadField, "umbracoFile", "Document file", "documentContent", mandatory: true);
        return mt;
    }

    private static void AddProperty(
        IContentTypeComposition mt,
        IShortStringHelper helper,
        IDataType dataType,
        string alias,
        string name,
        string groupAlias,
        bool mandatory)
    {
        var pt = new PropertyType(helper, dataType, alias)
        {
            Name = name,
            Mandatory = mandatory,
        };
        mt.AddPropertyType(pt, groupAlias);
    }
}
